fn main() {
    use std::io::Write;
    use std::path::{Path, PathBuf};

    fn gen_ax_config(out_file: &str) -> std::io::Result<()> {
        let mut output = Vec::new();
        writeln!(output, "//! Generated by build.rs, DO NOT edit!\n")?;
        writeln!(
            output,
            "#define AX_CONFIG_TASK_STACK_SIZE {:#x}",
            axconfig::TASK_STACK_SIZE,
        )?;

        std::fs::write(out_file, output)?;
        Ok(())
    }

    fn gen_rust_to_c_bindings(crate_dir: &Path, out_file: &str) {
        // load configs from "cbindgen.toml"
        cbindgen::generate(crate_dir)
            .expect("Unable to generate rust->c bindings")
            .write_to_file(out_file);
    }

    let crate_dir = PathBuf::from(&std::env::var("CARGO_MANIFEST_DIR").unwrap());
    gen_rust_to_c_bindings(&crate_dir, "include_gen/axlibc.h");
    gen_ax_config("include_gen/axconfig.h").unwrap();
}
